spring:
  datasource:
    url: jdbc:mysql://hnd1.clusters.zeabur.com:31911/ticket-grabber
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: UYV037TPkXbOc68u54t9swvpy1zK2GCq
