spring:
  application:
    name: order-service
  config:
    import: "configserver:http://localhost:8888"

  data:
    redis:
      cluster:
        nodes:
          - 192.168.0.109:7001
          - 192.168.0.109:7002
          - 192.168.0.109:7003
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 30s
      timeout: 6000ms

  datasource:
    url: jdbc:mysql://hnd1.clusters.zeabur.com:31911/ticket-grabber
    username: root
    password: UYV037TPkXbOc68u54t9swvpy1zK2GCq

mybatis:
  mapper-locations: classpath:mapper/*.xml
