spring:
  data:
    redis:
      cluster:
        nodes:
          - 192.168.0.109:7001
          - 192.168.0.109:7002
          - 192.168.0.109:7003
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 30s
      timeout: 6000ms

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  issuer: ticket-grabber
  expire: 720

key:
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDAMWVFi8JNG3Ukq5LSDJQZlTEoqedEZnWib+dHDSEsINhxp698rcyYD+4wAD1EUPGRS9Ag47CRUS4Q7qsEfaaBT3ZTyiutf82P+rTiOwGiBva/C9/eUhLsX9PG1T3ePliB9i+tAwWCcbYrl5MhW/452bnzGNEBij8SA83SPFclowIDAQAB
  privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAMAxZUWLwk0bdSSrktIMlBmVMSip50RmdaJv50cNISwg2HGnr3ytzJgP7jAAPURQ8ZFL0CDjsJFRLhDuqwR9poFPdlPKK61/zY/6tOI7AaIG9r8L395SEuxf08bVPd4+WIH2L60DBYJxtiuXkyFb/jnZufMY0QGKPxIDzdI8VyWjAgMBAAECgYAZdTGN8cJOBmoQ7m0nR6VCckGtuju5Er1YQ+xlu/Z96ufgvi5/nGHyboHFd/KlnvcwoNMz2BUmWpN4iLS8hoxMb28AuLXYaNDF3L8MV3w9R5GukbQ8CyUXqhXKnmVbvyX1QUdkg91fbLqvA3hW+t+Htkbzi0nYENqLtMWbmAop2QJBAPqr1COylKgSRf4SlZBC1ZPLSTKg/SoZ95bKAPwdwVQe5F04CN5ksfQyplIZy0K3dZXW9xXti1sTwoILTtbGewUCQQDER1LsQid6xlPhTLfB/ttvsO02JNj572CuzvMb+q+zHhb/5ZHwuslKsyduP29OX1B3AJFelwsduQWCBBZpyg6HAkEA8mbdQxP7GzhohNRV22Y2ALCxfQsfJepseV2obCUeAgnJjbeVI/I9/8ZG/dfBrieYxqhU0difTRijnHvw5lKTPQJAX/j0DfvG7Bx/tUFa9KuWRoW/Z2MbCRLINpGQg9TPBokm+9cXxhq/BByXoiu4VBz87kND0XmPgOgQTmOLRgz7jwJAE063S8/qGS+Xhi8tR2wrFdH9HCPWIkFSZzY/Tm+oCc4o/o7ptm3iPbBYDDKygtJ4ZPBzGwDgc9mROuqIR8sOxA==