spring:
  data:
    redis:
      cluster:
        nodes:
          - 192.168.0.109:7001 # TODO 改成自己的 ip
          - 192.168.0.109:7002 # TODO 改成自己的 ip
          - 192.168.0.109:7003 # TODO 改成自己的 ip
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 30s
      timeout: 6000ms

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest