#server:
#  port: 8082

spring:
  application:
    name: ticket-service
  config:
    import: "configserver:http://localhost:8888"

  datasource:
    url: jdbc:mysql://hnd1.clusters.zeabur.com:31911/ticket-grabber
    username: root
    password: UYV037TPkXbOc68u54t9swvpy1zK2GCq

mybatis:
  mapper-locations: classpath:mapper/*.xml
